version: 2

jobs:
  Build:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run:
          name: Mise à jour des paquets
          command: sudo apt update
      - run:
          name: Installation de NodeJS
          command: sudo apt install -y npm
      - restore_cache:
          name: Restauration du cache des dépendances PHP
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-
      - restore_cache:
          name: Restauration du cache des dépendances NodeJS
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
      - run:
          name: Installation des dépendances PHP
          command: composer install --prefer-dist --no-interaction
      - run:
          name: Installation des dépendances NodeJS
          command: npm install
      - save_cache:
          name: Sauvegarde du cache des dépendances PHP
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - save_cache:
          name: Sauvegarde du cache des dépendances NodeJS
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  Test:
    docker:
      - image: cimg/php:8.2-node
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: pass
    steps:
      - checkout
      - run:
          name: Mise à jour des paquets
          command: sudo apt update
      - run:
          name: Installation de NodeJS
          command: sudo apt install -y npm
      - run:
          name: Visualisation de la version NodeJs
          command: node -v
      - run:
          name: Visualisation de la version npm
          command: npm -v
      - restore_cache:
          name: Restauration du cache des dépendances PHP
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-
      - restore_cache:
          name: Restauration du cache des dépendances NodeJS
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
      - run:
          name: Initialiation de la variable environnement APP_ENV à test
          command: echo "APP_ENV=test" >> .env.local
      - run:
          name: Initialiation de la variable environnement DATABASE_URL
          command: echo "DATABASE_URL=mysql://root:pass@127.0.0.1/test" >> .env.test.local
      - run:
          name: Initialisation de l'application
          command: php bin/console app:init
      - run:
          name: Génération des assets
          command: npm run build
      - run:
          name: Lancement des tests
          command: SYMFONY_DEPRECATIONS_HELPER=disabled php bin/phpunit

  Quality:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run:
          name: Mise à jour des paquets
          command: sudo apt update
      - restore_cache:
          name: Restauration du cache des dépendances PHP
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-
      - run:
          name: Création du fichier phpstan.neon
          command: cp phpstan.dist.neon phpstan.neon
      - run:
          name: Lancement de l'analyse de code
          command: composer phpstan

workflows:
  version: 2
  Build Test and Deploy:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Quality:
          requires:
            - Build
